In [1]:
import pandas as pd 

In [2]:
import numpy as np

In [3]:
df = pd.read_excel(r'C:\Users\std03\Desktop\New Microsoft Excel Worksheet.xlsx')

In [4]:
df = df.dropna()

In [5]:
df.shape

(62, 4)

In [6]:
df['new'] = np.where((df['pain']>=2) & (df['pain']<=6),1,np.where((df['pain']==7)| (df['pain']==8),2,3))

In [3]:
from sklearn.neighbors import KNeighborsClassifier

In [19]:
x =(np.array(df[['thc','cbd']]).reshape(-1,2))

In [20]:
y = y=np.array(df[['new']]).reshape(-1,1)

In [9]:
from sklearn.model_selection import train_test_split

In [22]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.30, random_state = 0)

In [25]:
classifier.fit(x_train, y_train)

C:\Users\std03\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:179: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier()

In [67]:
classifier = KNeighborsClassifier(n_neighbors = 7)

In [68]:
classifier.fit(x_train, y_train)

C:\Users\std03\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:179: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier(n_neighbors=7)

In [69]:
print(classifier.predict(x_test))

[3 2 3 2 1 2 2 1 1 1 2 3 3 2 2]


In [70]:
print(classifier.score(x_test,y_test))

0.5333333333333333


In [7]:
df = pd.read_excel(r"C:\Users\std03\Desktop\New Microsoft Excel Worksheet.xlsx")

In [8]:
df = df.dropna()

In [9]:
df.shape

(59, 3)

In [10]:
x =(np.array(df[['thc','Frequency of use:']]).reshape(-1,2))

In [12]:
y=np.array(df[['new']]).reshape(-1,1)

In [13]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.30, random_state = 0)

In [68]:
classifier = KNeighborsClassifier(n_neighbors = 3)

In [69]:
classifier.fit(x_train, y_train)

C:\Users\std03\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:179: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier(n_neighbors=3)

In [70]:
print(classifier.predict(x_test))

[1 3 2 3 3 1 2 1 1 1 2 2 1 2 2 3 3 2]


In [71]:
print(classifier.score(x_test,y_test))

0.5


In [5]:
df = pd.read_excel(r"C:\Users\std03\Desktop\New Microsoft Excel Worksheet.xlsx")

In [6]:
df['new'] = np.where((df['pain']>=2) & (df['pain']<=6),1,np.where((df['pain']==7)| (df['pain']==8),2,3))

In [8]:
df = df.dropna()

In [9]:
df.shape

(60, 4)

In [43]:
x =(np.array(df[['cbd','How long have you used medical cannabis?','Frequency of use:']]).reshape(-1,3))

In [44]:
y=np.array(df[['new']]).reshape(-1,1)

In [45]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.30, random_state = 0)

In [43]:
classifier = KNeighborsClassifier(n_neighbors = 10)

In [44]:
classifier.fit(x_train, y_train)

C:\Users\std03\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:179: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier(n_neighbors=10)

In [45]:
print(classifier.predict(x_test))

[2 2 3 2 2 2 2 2 2 2 1 2 2 1 2 3 3 2]


In [46]:
print(classifier.score(x_test,y_test))

0.4444444444444444


In [5]:
df = pd.read_excel(r"C:\Users\std03\Desktop\New Microsoft Excel Worksheet.xlsx")

In [6]:
df = df.dropna()

In [7]:
df['new'] = np.where((df['pain']>=2) & (df['pain']<=6),1,np.where((df['pain']==7)| (df['pain']==8),2,3))

In [49]:
x =(np.array(df[['cbd','How long have you used medical cannabis?','Frequency of use:']]).reshape(-1,3))

In [50]:
y=np.array(df[['new']]).reshape(-1,1)

In [51]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.30, random_state = 0)

In [55]:
classifier = KNeighborsClassifier(n_neighbors = 6)

In [56]:
classifier.fit(x_train, y_train)

C:\Users\std03\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:179: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier(n_neighbors=6)

In [57]:
print(classifier.predict(x_test))

[1 2 2 2 1 1 2 2 1 2 2 2 3 2 2 3 1 1]


In [58]:
print(classifier.score(x_test,y_test))

0.4444444444444444


In [11]:
from sklearn.linear_model import LogisticRegression

In [60]:
model = LogisticRegression(solver='newton-cg', C=10.0, random_state=0)

In [61]:
model = model.fit(x_train,y_train)

C:\Users\std03\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


In [62]:
model.coef_[0]

array([-0.00381318,  0.41562014, -0.6959613 ])

In [63]:
model.predict(x_test)

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2])

In [64]:
model.score(x,y)

0.4838709677419355

In [57]:
from sklearn.metrics import classification_report, confusion_matrix

In [58]:
print(classification_report(y, model.predict(x)))

              precision    recall  f1-score   support

           1       1.00      0.13      0.24        15
           2       0.48      1.00      0.65        29
           3       0.00      0.00      0.00        18

    accuracy                           0.50        62
   macro avg       0.49      0.38      0.30        62
weighted avg       0.47      0.50      0.36        62



C:\Users\std03\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\std03\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\std03\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
x =(np.array(df[['cbd','How long have you used medical cannabis?','Frequency of use:']]).reshape(-1,3))

In [ ]:
y=np.array(df[['pain']]).reshape(-1,1)

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.30, random_state = 0)

In [87]:
model = LogisticRegression(solver='newton-cg', C=10.0, random_state=0)
model = model.fit(x, y)

C:\Users\std03\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


In [96]:
model.coef_[0]

array([-0.00990497,  0.44830545, -1.48385332])

In [89]:
model.predict(x_test)

array([3, 2, 2, 3, 3, 1, 2, 1, 1, 2, 3, 2, 3, 1, 2, 3, 1, 2])

In [90]:
model.score(x,y) ### 61% with thc   ### 50% with cbd

0.6101694915254238

In [91]:
print(classification_report(y, model.predict(x)))

              precision    recall  f1-score   support

           1       0.64      0.60      0.62        15
           2       0.66      0.70      0.68        27
           3       0.50      0.47      0.48        17

    accuracy                           0.61        59
   macro avg       0.60      0.59      0.59        59
weighted avg       0.61      0.61      0.61        59



In [92]:
model.classes_

array([1, 2, 3])